# Generated by Django 4.2.4 on 2024-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gender_remove_cart_sneakers_cart_sneakers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sneakers_id',
            field=models.PositiveIntegerField(),
        ),
    ]
